// <auto-generated />
namespace Lambda.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201608201131528_v2DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
